const CLIENT_CONFIGURATION = {
	SENTIMENT_PAGE_SIZE: process.env.SENTIMENT_PAGE_SIZE || 5,
	SENTIMENT_PAGE_INTERVAL: process.env.SENTIMENT_PAGE_INTERVAL || 1000,
}

export default CLIENT_CONFIGURATION
