import TWITTER_API_PARAMS from "./TwitterApiParams"

const CLIENT_CONFIGURATION = {
	SENTIMENT_PAGE_SIZE: process.env.SENTIMENT_PAGE_SIZE || 5,
	SENTIMENT_PAGE_INTERVAL: process.env.SENTIMENT_PAGE_INTERVAL || 1000,
	TWITTER_API_SEARCH_ARCHIVE_TYPE: TWITTER_API_PARAMS.search_archive_type,
}

export default CLIENT_CONFIGURATION
