default:
  image: node:14-alpine

  before_script:
    - npm ci

cache:
  paths:
    - node_modules/

stages:
  - build
  - lint
  - test
  - sonar

build:
  stage: build

  script:
    - npm run build

  artifacts:
    paths:
      - dist

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

lint:
  stage: lint

  script:
    - npm run lint

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:
  stage: test

  script:
    - npm run test:ci

  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

sonar:
  stage: sonar

  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_HOST_URL: $SONAR_HOST_URL
    SONAR_TOKEN: $SONAR_TOKEN
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.projectVersion=1.0

  needs: ["test"]

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
