image: node:14-alpine

before_script:
	- npm install

cache:
	paths:
		- node_modules/

stages:
	- build
	- test

build:
	stage: build
	script:
		- npm run build
	artifacts:
		paths:
			- dist
	rules:
		- if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:
	stage: test
	script:
		- npm run lint
		- npm run test
	rules:
		- if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
