default:
  image: node:14-alpine

  before_script:
    - apt-get -y install default-jre
    - npm ci

cache:
  paths:
    - node_modules/

stages:
  - build
  - lint
  - test
  - sonar

build:
  stage: build

  script:
    - npm run build

  artifacts:
    paths:
      - dist

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

lint:
  stage: lint

  script:
    - npm run lint

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:
  stage: test

  script:
    - npm run test:ci

  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

sonar:
  stage: sonar

  script:
    - npm run sonar

  needs: ["test"]

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
