default:
  image: openjdk:latest

  before_script:
    - apt-get install -y curl && curl -sL https://deb.nodesource.com/setup_14.x | bash - && apt-get install -y nodejs && curl -L https://www.npmjs.com/install.sh | sh
    - npm ci

cache:
  paths:
    - node_modules/

stages:
  - build
  - lint
  - test
  - sonar

build:
  stage: build

  script:
    - npm run build

  artifacts:
    paths:
      - dist

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

lint:
  stage: lint

  script:
    - npm run lint

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:
  stage: test

  script:
    - npm run test:ci

  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

sonar:
  stage: sonar

  script:
    - npm run sonar

  needs: ["test"]

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
